#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

# Utility function to update cartridge configuration

function update-configuration {
    # SCL installs of python 2.7
    env_dir="${OPENSHIFT_PATTON_DIR}/env"
    sclpath=$(dirname $(scl enable python27 "which python"))
    rpmpath="${OPENSHIFT_PATTON_DIR}usr/local"
    echo "$OPENSHIFT_PATTON_DIR/virtenv/bin:$rpmpath/bin:${sclpath}" > $env_dir/OPENSHIFT_PATTON_PATH_ELEMENT

    local ld_path=$(LD_LIBRARY_PATH="" scl enable python27 "printenv LD_LIBRARY_PATH"):${rpmpath}/lib/lib64
    path_append ${LD_LIBRARY_PATH:-:} ${ld_path:-:} > $env_dir/LD_LIBRARY_PATH
    set_env_var 'OPENSHIFT_PATTON_LD_LIBRARY_PATH_ELEMENT' $ld_path $env_dir

    local man_path=$(MANPATH="" scl enable python27 "printenv MANPATH")
    path_append ${MANPATH:-:} ${man_path:-:} > $env_dir/MANPATH

    local xdg_data_dirs=$(XDG_DATA_DIRS="" scl enable python27 "printenv XDG_DATA_DIRS")
    path_append ${XDG_DATA_DIRS:-:} ${xdg_data_dirs:-:} > $env_dir/XDG_DATA_DIRS

    local pkg_config_path=$(PKG_CONFIG_PATH="" scl enable python27 "printenv PKG_CONFIG_PATH")
    path_append ${PKG_CONFIG_PATH:-:} ${pkg_config_path:-:} > $env_dir/PKG_CONFIG_PATH

    echo "$OPENSHIFT_PATTON_DIR/virtenv" > $env_dir/VIRTUAL_ENV
}
