#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

# Utility function to update cartridge configuration

function update-configuration {
    # SCL installs of python 2.7
    sclpath=$(dirname $(scl enable python27 "which python"))
    echo "$OPENSHIFT_PATTON_DIR/virtenv/bin:$OPENSHIFT_PATTON_DIR/bin:${sclpath}" > $OPENSHIFT_PATTON_DIR/env/OPENSHIFT_PATTON_PATH_ELEMENT

    local ld_path=$(LD_LIBRARY_PATH="" scl enable python27 "printenv LD_LIBRARY_PATH")
    path_append ${LD_LIBRARY_PATH:-:} ${ld_path:-:} > $OPENSHIFT_PATTON_DIR/env/LD_LIBRARY_PATH

    local man_path=$(MANPATH="" scl enable python27 "printenv MANPATH")
    path_append ${MANPATH:-:} ${man_path:-:} > $OPENSHIFT_PATTON_DIR/env/MANPATH

    local xdg_data_dirs=$(XDG_DATA_DIRS="" scl enable python27 "printenv XDG_DATA_DIRS")
    path_append ${XDG_DATA_DIRS:-:} ${xdg_data_dirs:-:} > $OPENSHIFT_PATTON_DIR/env/XDG_DATA_DIRS

    local pkg_config_path=$(PKG_CONFIG_PATH="" scl enable python27 "printenv PKG_CONFIG_PATH")
    path_append ${PKG_CONFIG_PATH:-:} ${pkg_config_path:-:} > $OPENSHIFT_PATTON_DIR/env/PKG_CONFIG_PATH

    echo "$OPENSHIFT_PATTON_DIR/virtenv" > $OPENSHIFT_PATTON_DIR/env/VIRTUAL_ENV
}
