#!/bin/bash

# Make sure the USER environment variable is set. Honcho needs it
# and if it isn't set by openshift, then honcho gets very, very
# angry.

function ensure_user_env_var() {
  if [[ "x${USER}x" == "xx" ]]; then
    USER=`id -un`
    export USER
  fi
}  #  End of function  ensure_user_env_var.

function create_supervisor_config() {
  pushd "$OPENSHIFT_REPO_DIR" > /dev/null

    mkdir -p $OPENSHIFT_PATTON_RUN_DIR

    ensure_user_env_var

    if [ -f "${PROJECT_PROCFILE}" ]; then
      honcho check --app-root ${OPENSHIFT_REPO_DIR} --procfile ${PROJECT_PROCFILE} 2> /dev/null
      if [[ $? == 0 ]]; then

       echo Creating supervisord.conf from ${PROJECT_PROCFILE}

       honcho export \
         --app-root ${OPENSHIFT_REPO_DIR} \
         --procfile ${PROJECT_PROCFILE} \
         --log $OPENSHIFT_PATTON_LOG_DIR \
         --port $OPENSHIFT_PATTON_PORT \
         -a ${OPENSHIFT_APP_NAME} \
         supervisord ${OPENSHIFT_PYTHON_DIR}etc/supervisor.d/
     fi
    fi
  popd  > /dev/null

}  #  End of function  create_supervisor_config.


function is_running() {
   pushd $OPENSHIFT_REPO_DIR > /dev/null
   if [ -w ${OPENSHIFT_PATTON_RUN_DIR}supervisor.sock ];
   then
    return 0
   else
  return 1
   fi
}  #  End of function  _is_running.

